// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS.Main.Dal;

#nullable disable

namespace POS.Main.Dal.Migrations
{
    [DbContext(typeof(POSMainContext))]
    [Migration("20260317100000_ReorderModuleSortOrder")]
    partial class ReorderModuleSortOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POS.Main.Dal.Entities.TbAuthorizeMatrixPosition", b =>
                {
                    b.Property<int>("AuthMatrixPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthMatrixPositionId"));

                    b.Property<int>("AuthorizeMatrixId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("AuthMatrixPositionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteFlag")
                        .HasDatabaseName("IX_TbAuthMatrixPositions_DeleteFlag");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("IX_TbAuthMatrixPositions_PositionId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("AuthorizeMatrixId", "PositionId")
                        .IsUnique()
                        .HasDatabaseName("IX_TbAuthMatrixPositions_Matrix_Position");

                    b.ToTable("TbAuthorizeMatrixPositions", (string)null);
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbEmployee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstNameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstNameThai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("ImageFileId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFullTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastNameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastNameThai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LineId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("Religion")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteFlag")
                        .HasDatabaseName("IX_Employees_DeleteFlag");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Employees_Email");

                    b.HasIndex("FirstNameThai")
                        .HasDatabaseName("IX_Employees_FirstNameThai");

                    b.HasIndex("ImageFileId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Employees_IsActive");

                    b.HasIndex("LastNameThai")
                        .HasDatabaseName("IX_Employees_LastNameThai");

                    b.HasIndex("NationalId")
                        .HasDatabaseName("IX_Employees_NationalId");

                    b.HasIndex("Phone")
                        .HasDatabaseName("IX_Employees_Phone");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("IX_Employees_PositionId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Employees_UserId")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("TbEmployees", (string)null);
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbEmployeeAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Building")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Moo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Road")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Soi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Yaek")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AddressId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_EmployeeAddresses_EmployeeId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("TbEmployeeAddresses", (string)null);
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbEmployeeEducation", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Gpa")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("int");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Major")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("EducationId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_EmployeeEducations_EmployeeId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("TbEmployeeEducations", (string)null);
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbEmployeeWorkHistory", b =>
                {
                    b.Property<int>("WorkHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkHistoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("WorkPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Workplace")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("WorkHistoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_EmployeeWorkHistories_EmployeeId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("TbEmployeeWorkHistories", (string)null);
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbFile", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("FileId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteFlag");

                    b.HasIndex("S3Key")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("TbFiles", (string)null);
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ImageFileId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameThai")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("MenuId");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Menus_Category");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteFlag")
                        .HasDatabaseName("IX_Menus_DeleteFlag");

                    b.HasIndex("ImageFileId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Menus_IsActive");

                    b.HasIndex("IsAvailable")
                        .HasDatabaseName("IX_Menus_IsAvailable");

                    b.HasIndex("NameEnglish")
                        .HasDatabaseName("IX_Menus_NameEnglish");

                    b.HasIndex("NameThai")
                        .HasDatabaseName("IX_Menus_NameThai");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("TbMenus", (string)null);
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbPasswordHistory", b =>
                {
                    b.Property<int>("PasswordHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PasswordHistoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PasswordHistoryId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_PasswordHistory_UserId");

                    b.ToTable("TbPasswordHistory", (string)null);
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbPasswordResetToken", b =>
                {
                    b.Property<Guid>("PasswordResetTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("OtpAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("OtpExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OtpVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ResetToken")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ResetTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PasswordResetTokenId");

                    b.HasIndex("ResetToken")
                        .HasDatabaseName("IX_PasswordResetTokens_ResetToken");

                    b.HasIndex("UserId", "IsUsed")
                        .HasDatabaseName("IX_PasswordResetTokens_UserUsed");

                    b.ToTable("TbPasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbRefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.ToTable("TbRefreshTokens", (string)null);
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbServiceCharge", b =>
                {
                    b.Property<int>("ServiceChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceChargeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PercentageRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ServiceChargeId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteFlag")
                        .HasDatabaseName("IX_ServiceCharges_DeleteFlag");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("IX_ServiceCharges_EndDate");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ServiceCharges_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_ServiceCharges_Name");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("IX_ServiceCharges_StartDate");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("TbServiceCharges", (string)null);
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbShopOperatingHour", b =>
                {
                    b.Property<int>("ShopOperatingHourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopOperatingHourId"));

                    b.Property<TimeSpan?>("CloseTime1")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("CloseTime2")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<TimeSpan?>("OpenTime1")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("OpenTime2")
                        .HasColumnType("time");

                    b.Property<int>("ShopSettingsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ShopOperatingHourId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteFlag")
                        .HasDatabaseName("IX_ShopOperatingHours_DeleteFlag");

                    b.HasIndex("ShopSettingsId")
                        .HasDatabaseName("IX_ShopOperatingHours_ShopSettingsId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("ShopSettingsId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("IX_ShopOperatingHours_Settings_Day");

                    b.ToTable("TbShopOperatingHours", (string)null);

                    b.HasData(
                        new
                        {
                            ShopOperatingHourId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 1,
                            DeleteFlag = false,
                            IsOpen = false,
                            ShopSettingsId = 1
                        },
                        new
                        {
                            ShopOperatingHourId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 2,
                            DeleteFlag = false,
                            IsOpen = false,
                            ShopSettingsId = 1
                        },
                        new
                        {
                            ShopOperatingHourId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 3,
                            DeleteFlag = false,
                            IsOpen = false,
                            ShopSettingsId = 1
                        },
                        new
                        {
                            ShopOperatingHourId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 4,
                            DeleteFlag = false,
                            IsOpen = false,
                            ShopSettingsId = 1
                        },
                        new
                        {
                            ShopOperatingHourId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 5,
                            DeleteFlag = false,
                            IsOpen = false,
                            ShopSettingsId = 1
                        },
                        new
                        {
                            ShopOperatingHourId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 6,
                            DeleteFlag = false,
                            IsOpen = false,
                            ShopSettingsId = 1
                        },
                        new
                        {
                            ShopOperatingHourId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 7,
                            DeleteFlag = false,
                            IsOpen = false,
                            ShopSettingsId = 1
                        });
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbShopSettings", b =>
                {
                    b.Property<int>("ShopSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopSettingsId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("CompanyNameEnglish")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyNameThai")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Facebook")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FoodType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("HasTwoPeriods")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Instagram")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LineId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LogoFileId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentQrCodeFileId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShopEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShopNameEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShopNameThai")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ShopSettingsId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteFlag")
                        .HasDatabaseName("IX_ShopSettings_DeleteFlag");

                    b.HasIndex("LogoFileId")
                        .HasDatabaseName("IX_ShopSettings_LogoFileId");

                    b.HasIndex("PaymentQrCodeFileId")
                        .HasDatabaseName("IX_ShopSettings_PaymentQrCodeFileId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("TbShopSettings", (string)null);

                    b.HasData(
                        new
                        {
                            ShopSettingsId = 1,
                            Address = "",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            FoodType = "",
                            HasTwoPeriods = false,
                            PhoneNumber = "",
                            ShopNameEnglish = "",
                            ShopNameThai = "",
                            TaxId = ""
                        });
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("AutoUnlockDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLockedByAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPasswordChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<int>("LockoutCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PinCodeHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteFlag")
                        .HasDatabaseName("IX_Users_DeleteFlag");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Users_IsActive");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("TbUsers", (string)null);
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbmAuthorizeMatrix", b =>
                {
                    b.Property<int>("AuthorizeMatrixId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorizeMatrixId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionPath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("AuthorizeMatrixId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteFlag")
                        .HasDatabaseName("IX_TbmAuthorizeMatrices_DeleteFlag");

                    b.HasIndex("PermissionId");

                    b.HasIndex("PermissionPath")
                        .IsUnique()
                        .HasDatabaseName("IX_TbmAuthorizeMatrices_PermissionPath");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("ModuleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_TbmAuthorizeMatrices_Module_Permission");

                    b.ToTable("TbmAuthorizeMatrices", (string)null);

                    b.HasData(
                        new
                        {
                            AuthorizeMatrixId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 9,
                            PermissionId = 1,
                            PermissionPath = "dashboard.view.read"
                        },
                        new
                        {
                            AuthorizeMatrixId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 10,
                            PermissionId = 1,
                            PermissionPath = "service-charge.read"
                        },
                        new
                        {
                            AuthorizeMatrixId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 10,
                            PermissionId = 2,
                            PermissionPath = "service-charge.create"
                        },
                        new
                        {
                            AuthorizeMatrixId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 10,
                            PermissionId = 3,
                            PermissionPath = "service-charge.update"
                        },
                        new
                        {
                            AuthorizeMatrixId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 10,
                            PermissionId = 4,
                            PermissionPath = "service-charge.delete"
                        },
                        new
                        {
                            AuthorizeMatrixId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 11,
                            PermissionId = 1,
                            PermissionPath = "position.read"
                        },
                        new
                        {
                            AuthorizeMatrixId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 11,
                            PermissionId = 2,
                            PermissionPath = "position.create"
                        },
                        new
                        {
                            AuthorizeMatrixId = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 11,
                            PermissionId = 3,
                            PermissionPath = "position.update"
                        },
                        new
                        {
                            AuthorizeMatrixId = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 11,
                            PermissionId = 4,
                            PermissionPath = "position.delete"
                        },
                        new
                        {
                            AuthorizeMatrixId = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 12,
                            PermissionId = 1,
                            PermissionPath = "employee.read"
                        },
                        new
                        {
                            AuthorizeMatrixId = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 12,
                            PermissionId = 2,
                            PermissionPath = "employee.create"
                        },
                        new
                        {
                            AuthorizeMatrixId = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 12,
                            PermissionId = 3,
                            PermissionPath = "employee.update"
                        },
                        new
                        {
                            AuthorizeMatrixId = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 12,
                            PermissionId = 4,
                            PermissionPath = "employee.delete"
                        },
                        new
                        {
                            AuthorizeMatrixId = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 13,
                            PermissionId = 1,
                            PermissionPath = "menu-item.read"
                        },
                        new
                        {
                            AuthorizeMatrixId = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 13,
                            PermissionId = 2,
                            PermissionPath = "menu-item.create"
                        },
                        new
                        {
                            AuthorizeMatrixId = 16,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 13,
                            PermissionId = 3,
                            PermissionPath = "menu-item.update"
                        },
                        new
                        {
                            AuthorizeMatrixId = 17,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 13,
                            PermissionId = 4,
                            PermissionPath = "menu-item.delete"
                        },
                        new
                        {
                            AuthorizeMatrixId = 18,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 14,
                            PermissionId = 1,
                            PermissionPath = "order-manage.read"
                        },
                        new
                        {
                            AuthorizeMatrixId = 19,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 14,
                            PermissionId = 2,
                            PermissionPath = "order-manage.create"
                        },
                        new
                        {
                            AuthorizeMatrixId = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 14,
                            PermissionId = 3,
                            PermissionPath = "order-manage.update"
                        },
                        new
                        {
                            AuthorizeMatrixId = 21,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 14,
                            PermissionId = 4,
                            PermissionPath = "order-manage.delete"
                        },
                        new
                        {
                            AuthorizeMatrixId = 22,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 15,
                            PermissionId = 1,
                            PermissionPath = "table-manage.read"
                        },
                        new
                        {
                            AuthorizeMatrixId = 23,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 15,
                            PermissionId = 2,
                            PermissionPath = "table-manage.create"
                        },
                        new
                        {
                            AuthorizeMatrixId = 24,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 15,
                            PermissionId = 3,
                            PermissionPath = "table-manage.update"
                        },
                        new
                        {
                            AuthorizeMatrixId = 25,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 15,
                            PermissionId = 4,
                            PermissionPath = "table-manage.delete"
                        },
                        new
                        {
                            AuthorizeMatrixId = 26,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 16,
                            PermissionId = 1,
                            PermissionPath = "payment-manage.read"
                        },
                        new
                        {
                            AuthorizeMatrixId = 27,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 16,
                            PermissionId = 2,
                            PermissionPath = "payment-manage.create"
                        },
                        new
                        {
                            AuthorizeMatrixId = 28,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 16,
                            PermissionId = 3,
                            PermissionPath = "payment-manage.update"
                        },
                        new
                        {
                            AuthorizeMatrixId = 29,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 16,
                            PermissionId = 4,
                            PermissionPath = "payment-manage.delete"
                        },
                        new
                        {
                            AuthorizeMatrixId = 30,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 17,
                            PermissionId = 1,
                            PermissionPath = "kitchen-order.read"
                        },
                        new
                        {
                            AuthorizeMatrixId = 31,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 17,
                            PermissionId = 3,
                            PermissionPath = "kitchen-order.update"
                        },
                        new
                        {
                            AuthorizeMatrixId = 32,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 18,
                            PermissionId = 1,
                            PermissionPath = "shop-settings.read"
                        },
                        new
                        {
                            AuthorizeMatrixId = 33,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            ModuleId = 18,
                            PermissionId = 3,
                            PermissionPath = "shop-settings.update"
                        });
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbmModule", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentModuleId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ModuleId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteFlag")
                        .HasDatabaseName("IX_TbmModules_DeleteFlag");

                    b.HasIndex("ModuleCode")
                        .IsUnique()
                        .HasDatabaseName("IX_TbmModules_ModuleCode");

                    b.HasIndex("ParentModuleId")
                        .HasDatabaseName("IX_TbmModules_ParentModuleId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("TbmModules", (string)null);

                    b.HasData(
                        new
                        {
                            ModuleId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "dashboard",
                            ModuleName = "แดชบอร์ด",
                            SortOrder = 1
                        },
                        new
                        {
                            ModuleId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "admin-settings",
                            ModuleName = "ตั้งค่าระบบ",
                            SortOrder = 2
                        },
                        new
                        {
                            ModuleId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "human-resource",
                            ModuleName = "ทรัพยากรบุคคล",
                            SortOrder = 3
                        },
                        new
                        {
                            ModuleId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "menu",
                            ModuleName = "เมนู",
                            SortOrder = 4
                        },
                        new
                        {
                            ModuleId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "order",
                            ModuleName = "ออเดอร์",
                            SortOrder = 5
                        },
                        new
                        {
                            ModuleId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "table",
                            ModuleName = "โต๊ะ",
                            SortOrder = 6
                        },
                        new
                        {
                            ModuleId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "payment",
                            ModuleName = "ชำระเงิน",
                            SortOrder = 7
                        },
                        new
                        {
                            ModuleId = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "kitchen-display",
                            ModuleName = "ครัว",
                            SortOrder = 8
                        },
                        new
                        {
                            ModuleId = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "dashboard.view",
                            ModuleName = "Dashboard",
                            ParentModuleId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            ModuleId = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "service-charge",
                            ModuleName = "Service Charge",
                            ParentModuleId = 2,
                            SortOrder = 1
                        },
                        new
                        {
                            ModuleId = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "position",
                            ModuleName = "จัดการตำแหน่ง",
                            ParentModuleId = 2,
                            SortOrder = 2
                        },
                        new
                        {
                            ModuleId = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "employee",
                            ModuleName = "จัดการพนักงาน",
                            ParentModuleId = 3,
                            SortOrder = 1
                        },
                        new
                        {
                            ModuleId = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "menu-item",
                            ModuleName = "จัดการเมนู",
                            ParentModuleId = 4,
                            SortOrder = 1
                        },
                        new
                        {
                            ModuleId = 18,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "shop-settings",
                            ModuleName = "ตั้งค่าร้านค้า",
                            ParentModuleId = 2,
                            SortOrder = 3
                        },
                        new
                        {
                            ModuleId = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "order-manage",
                            ModuleName = "จัดการออเดอร์",
                            ParentModuleId = 5,
                            SortOrder = 1
                        },
                        new
                        {
                            ModuleId = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "table-manage",
                            ModuleName = "จัดการโต๊ะ",
                            ParentModuleId = 6,
                            SortOrder = 1
                        },
                        new
                        {
                            ModuleId = 16,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "payment-manage",
                            ModuleName = "ชำระเงิน",
                            ParentModuleId = 7,
                            SortOrder = 1
                        },
                        new
                        {
                            ModuleId = 17,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            IsActive = true,
                            ModuleCode = "kitchen-order",
                            ModuleName = "แสดงออเดอร์ครัว",
                            ParentModuleId = 8,
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbmPermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("PermissionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteFlag")
                        .HasDatabaseName("IX_TbmPermissions_DeleteFlag");

                    b.HasIndex("PermissionCode")
                        .IsUnique()
                        .HasDatabaseName("IX_TbmPermissions_PermissionCode");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("TbmPermissions", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            PermissionCode = "read",
                            PermissionName = "แสดง",
                            SortOrder = 1
                        },
                        new
                        {
                            PermissionId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            PermissionCode = "create",
                            PermissionName = "เพิ่ม",
                            SortOrder = 2
                        },
                        new
                        {
                            PermissionId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            PermissionCode = "update",
                            PermissionName = "แก้ไข",
                            SortOrder = 3
                        },
                        new
                        {
                            PermissionId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            PermissionCode = "delete",
                            PermissionName = "ลบ",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbmPosition", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("PositionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteFlag")
                        .HasDatabaseName("IX_TbmPositions_DeleteFlag");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_TbmPositions_IsActive");

                    b.HasIndex("PositionName")
                        .IsUnique()
                        .HasDatabaseName("IX_TbmPositions_PositionName");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("TbmPositions", (string)null);

                    b.HasData(
                        new
                        {
                            PositionId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "ดูแลระบบทั้งหมด สิทธิ์เข้าถึงทุกฟังก์ชัน",
                            IsActive = true,
                            PositionName = "ผู้ดูแลระบบ"
                        },
                        new
                        {
                            PositionId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "จัดการร้านค้า ดูรายงาน จัดการพนักงาน",
                            IsActive = true,
                            PositionName = "ผู้จัดการ"
                        },
                        new
                        {
                            PositionId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "รับออเดอร์ ชำระเงิน",
                            IsActive = true,
                            PositionName = "แคชเชียร์"
                        });
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbAuthorizeMatrixPosition", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbmAuthorizeMatrix", "AuthorizeMatrix")
                        .WithMany("AuthorizeMatrixPositions")
                        .HasForeignKey("AuthorizeMatrixId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbmPosition", "Position")
                        .WithMany("AuthorizeMatrixPositions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AuthorizeMatrix");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Position");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbEmployee", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbFile", "ImageFile")
                        .WithMany()
                        .HasForeignKey("ImageFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbmPosition", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbUser", "User")
                        .WithOne("Employee")
                        .HasForeignKey("POS.Main.Dal.Entities.TbEmployee", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("ImageFile");

                    b.Navigation("Position");

                    b.Navigation("UpdatedByEmployee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbEmployeeAddress", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "Employee")
                        .WithMany("Addresses")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Employee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbEmployeeEducation", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "Employee")
                        .WithMany("Educations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Employee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbEmployeeWorkHistory", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "Employee")
                        .WithMany("WorkHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Employee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbFile", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbMenu", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbFile", "ImageFile")
                        .WithMany()
                        .HasForeignKey("ImageFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("ImageFile");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbPasswordHistory", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbPasswordResetToken", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbRefreshToken", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbServiceCharge", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbShopOperatingHour", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbShopSettings", "ShopSettings")
                        .WithMany("OperatingHours")
                        .HasForeignKey("ShopSettingsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("ShopSettings");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbShopSettings", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbFile", "LogoFile")
                        .WithMany()
                        .HasForeignKey("LogoFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbFile", "PaymentQrCodeFile")
                        .WithMany()
                        .HasForeignKey("PaymentQrCodeFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LogoFile");

                    b.Navigation("PaymentQrCodeFile");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbUser", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbmAuthorizeMatrix", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbmModule", "Module")
                        .WithMany("AuthorizeMatrices")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("POS.Main.Dal.Entities.TbmPermission", "Permission")
                        .WithMany("AuthorizeMatrices")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Module");

                    b.Navigation("Permission");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbmModule", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbmModule", "ParentModule")
                        .WithMany("ChildModules")
                        .HasForeignKey("ParentModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("ParentModule");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbmPermission", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbmPosition", b =>
                {
                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Main.Dal.Entities.TbEmployee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbEmployee", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Educations");

                    b.Navigation("WorkHistories");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbShopSettings", b =>
                {
                    b.Navigation("OperatingHours");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbUser", b =>
                {
                    b.Navigation("Employee");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbmAuthorizeMatrix", b =>
                {
                    b.Navigation("AuthorizeMatrixPositions");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbmModule", b =>
                {
                    b.Navigation("AuthorizeMatrices");

                    b.Navigation("ChildModules");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbmPermission", b =>
                {
                    b.Navigation("AuthorizeMatrices");
                });

            modelBuilder.Entity("POS.Main.Dal.Entities.TbmPosition", b =>
                {
                    b.Navigation("AuthorizeMatrixPositions");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
